analyzer:
  exclude:
    - /**/*.g.dart

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    prefer_relative_imports: true
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
